package com.example.currencyconverter.view.recyclerview

class RateUI {
    val shortNameList = listOf<String>(
        "AUD"
        , "BGN"
        , "BRL"
        , "CAD"
        , "CHF"
        , "CNY"
        , "CZK"
        , "DKK"
        , "GBP"
        , "HKD"
        , "HRK"
        , "HUF"
        , "IDR"
        , "ILS"
        , "INR"
        , "ISK"
        , "JPY"
        , "KRW"
        , "MXN"
        , "MYR"
        , "NOK"
        , "NZD"
        , "PHP"
        , "PLN"
        , "RON"
        , "RUB"
        , "SEK"
        , "SGD"
        , "THB"
        , "USD"
        , "ZAR"
    )

    val fullNameList = listOf<String>(
        "Australian Dollar"
        , "Bulgarian Lev"
        , "Brazilian Real"
        , "Canadian Dollar"
        , "Confoederatio Helvetica Franc"
        , "Chinese Yuan"
        , "Czech Koruna"
        , "Denmark Krone"
        , "Great Britain Pound"
        , "Hong Kong dollar"
        , "Kuna"
        , "Hungarian Forint"
        , "Indonesian Rupiah"
        , "Israeli new shekel"
        , "Indian Rupee"
        , "Iceland Krona"
        , "Japanese Yen"
        , "South Korean Won"
        , "Mexican Peso"
        , "Ringgit Malaysia"
        , "Norwegian Krone"
        , "New Zealand Dollar"
        , "Philippine Peso"
        , "Polish Zloty"
        , "Romanian New Leu"
        , "Russian Ruble"
        , "Swedish Krona"
        , "Singapore Dollar"
        , "Thailand Baht"
        , "United States Dollar"
        , "South African Rand"
    )
}