package com.example.currencyconverter.view.recyclerview

class RateUI {
        val shortNameList = mapOf<String,String>(
         "AUD" to "AUD"
        , "BGN" to "BGN"
        , "BRL" to "BRL"
        , "CAD" to "CAD"
        , "CHF" to "CHF"
        , "CNY" to "CNY"
        , "CZK" to "CZK"
        , "DKK" to "DKK"
        , "GBP" to "GBP"
        , "HKD" to "HKD"
        , "HRK" to "HRK"
        , "HUF" to "HUF"
        , "IDR" to "IDR"
        , "ILS" to "ILS"
        , "INR" to "INR"
        , "ISK" to "ISK"
        , "JPY" to "JPY"
        , "KRW" to "KRW"
        , "MXN" to "MXN"
        , "MYR" to "MYR"
        , "NOK" to "NOK"
        , "NZD" to "NZD"
        , "PHP" to "PHP"
        , "PLN" to "PLN"
        , "RON" to "RON"
        , "RUB" to "RUB"
        , "SEK" to "SEK"
        , "SGD" to "SGD"
        , "THB" to "THB"
        , "USD" to "USD"
        , "ZAR" to "ZAR"
        )

        val fullNameList = mapOf<String, String>(
            "AUD" to "Australian Dollar"
            , "BGN" to "Bulgarian Lev"
            , "BRL" to "Brazilian Real"
            , "CAD" to "Canadian Dollar"
            , "CHF" to "Confoederatio Helvetica Franc"
            , "CNY" to "Chinese Yuan"
            , "CZK" to "Czech Koruna"
            , "DKK" to "Denmark Krone"
            , "GBP" to "Great Britain Pound"
            , "HKD" to "Hong Kong dollar"
            , "HRK" to "Kuna"
            , "HUF" to "Hungarian Forint"
            , "IDR" to "Indonesian Rupiah"
            , "ILS" to "Israeli new shekel"
            , "INR" to "Indian Rupee"
            , "ISK" to "Iceland Krona"
            , "JPY" to "Japanese Yen"
            , "KRW" to "South Korean Won"
            , "MXN" to "Mexican Peso"
            , "MYR" to "Ringgit Malaysia"
            , "NOK" to "Norwegian Krone"
            , "NZD" to "New Zealand Dollar"
            , "PHP" to "Philippine Peso"
            , "PLN" to "Polish Zloty"
            , "RON" to "Romanian New Leu"
            , "RUB" to "Russian Ruble"
            , "SEK" to "Swedish Krona"
            , "SGD" to "Singapore Dollar"
            , "THB" to "Thailand Baht"
            , "USD" to "United States Dollar"
            , "ZAR" to "South African Rand"
        )
}